export const SITE = {
  website: "https://www.stephenwhitlock.com/",
  author: "Stephen Whitlock",
  profile: "https://www.stephenwhitlock.com/",
  desc: "Stephen's Blog",
  title: "Stephen Whitlock",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 4,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  editPost: {
    enabled: true,
    text: "Edit page",
    url: "https://github.com/jshwi/stephenwhitlock/edit/master/",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "en",
  timezone: "Australia/Sydney",
} as const;
